# Generated by Django 4.0.1 on 2022-01-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Barcha Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='subject_extra_info',
            options={'verbose_name': "Fanga tegishli Ma'lumotga aloqador Ma'lumot", 'verbose_name_plural': "Fanga tegishli Ma'lumotlarga aloqador Ma'lumotlar"},
        ),
        migrations.AlterModelOptions(
            name='subject_info',
            options={'verbose_name': "Fanga tegishli Ma'lumot", 'verbose_name_plural': "Fanga tegishli Ma'lumotlar"},
        ),
    ]
