# Generated by Django 4.0.2 on 2022-02-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_alloma_allomamenu_alter_regions_name'),
        ('trunk', '0004_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name="Ma'lumot")),
                ('image', models.ImageField(upload_to='images', verbose_name="Rasm Qo'shish")),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.alloma', verbose_name='Ish Muallifi')),
            ],
            options={
                'verbose_name': "Jahon ilm-faniga qo'shgan hissasi",
                'verbose_name_plural': "Jahon ilm-faniga qo'shgan hissasi",
            },
        ),
    ]
