# Generated by Django 4.0.2 on 2022-02-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0005_woscience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Ilmiy Asar ', 'verbose_name_plural': 'Ilmiy Asarlar '},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan ', 'verbose_name_plural': 'Barcha Fanlar '},
        ),
        migrations.AlterModelOptions(
            name='subject_extra_info',
            options={'verbose_name': "Fanga tegishli Ma'lumotga aloqador Ma'lumot ", 'verbose_name_plural': "Fanga tegishli Ma'lumotlarga aloqador Ma'lumotlar "},
        ),
        migrations.AlterModelOptions(
            name='subject_info',
            options={'verbose_name': "Fanga tegishli Ma'lumot ", 'verbose_name_plural': "Fanga tegishli Ma'lumotlar "},
        ),
        migrations.AlterModelOptions(
            name='woscience',
            options={'verbose_name': "Jahon ilm-faniga qo'shgan hissasi ", 'verbose_name_plural': "Jahon ilm-faniga qo'shgan hissasi "},
        ),
        migrations.RenameField(
            model_name='woscience',
            old_name='author_id',
            new_name='author',
        ),
    ]
