# Generated by Django 4.0.2 on 2022-02-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0006_alter_books_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='woscience',
            old_name='author',
            new_name='author_id',
        ),
    ]
