# Generated by Django 4.0.2 on 2022-06-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0008_remove_woscience_author_id_remove_subject_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_info',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject_Extra_Info',
        ),
        migrations.DeleteModel(
            name='Subject_Info',
        ),
    ]
