# Generated by Django 4.0.1 on 2022-01-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_alloma_allomamenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alloma',
            options={'verbose_name': 'Alloma', 'verbose_name_plural': 'Allomalar'},
        ),
        migrations.AlterModelOptions(
            name='allomamenu',
            options={'verbose_name': 'Alloma Tarmoq Menyusi', 'verbose_name_plural': 'Alloma Tarmoqlar Menyulari'},
        ),
        migrations.AlterModelOptions(
            name='century',
            options={'verbose_name': 'Asr', 'verbose_name_plural': 'Asrlar'},
        ),
        migrations.AlterModelOptions(
            name='madrasa',
            options={'verbose_name': 'Madrasa', 'verbose_name_plural': 'Barcha Madrasalar'},
        ),
    ]
