# Generated by Django 4.0.2 on 2022-02-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_alloma_options_alter_allomamenu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloma',
            name='about',
            field=models.TextField(null=True, verbose_name="Alloma haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='alloma',
            name='allomamenu',
            field=models.ManyToManyField(blank=True, null=True, to='base.AllomaMenu', verbose_name="Allomaga tegishli yo'nalishlar"),
        ),
        migrations.AlterField(
            model_name='alloma',
            name='birth_area',
            field=models.CharField(max_length=50, null=True, verbose_name="Tug'ilgan joyi"),
        ),
        migrations.AlterField(
            model_name='alloma',
            name='birth_year',
            field=models.CharField(max_length=30, null=True, verbose_name="Tug'ilgan yili"),
        ),
        migrations.AlterField(
            model_name='alloma',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Allomaning rasmi'),
        ),
        migrations.AlterField(
            model_name='alloma',
            name='madrasa_alloma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.madrasa', verbose_name='Alloma mansub madrasa'),
        ),
        migrations.AlterField(
            model_name='alloma',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Alloma ismi'),
        ),
        migrations.AlterField(
            model_name='allomamenu',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Menyu nomi'),
        ),
        migrations.AlterField(
            model_name='century',
            name='century',
            field=models.CharField(max_length=100, verbose_name='Asr'),
        ),
        migrations.AlterField(
            model_name='century',
            name='sum_madrasa',
            field=models.CharField(max_length=100, null=True, verbose_name='Madrasalar soni'),
        ),
        migrations.AlterField(
            model_name='madrasa',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Madrasa nomi'),
        ),
        migrations.AlterField(
            model_name='madrasa',
            name='relevant_century',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.century', verbose_name="Madrasa mavjud bo'lgan asr"),
        ),
    ]
