# Generated by Django 4.0.2 on 2022-02-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_alloma_about_alter_alloma_allomamenu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madrasa',
            old_name='relevant_century',
            new_name='century_id',
        ),
    ]
