# Generated by Django 4.0.2 on 2022-02-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_relevant_century_madrasa_century_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Madrasa joylashgan shahar nomi')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
            },
        ),
        migrations.AddField(
            model_name='madrasa',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.regions', verbose_name='Madrasa joylashgan shahar'),
        ),
    ]
