# Generated by Django 4.0.2 on 2022-02-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_regions_madrasa_region_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloma',
            name='allomamenu',
            field=models.ManyToManyField(blank=True, to='base.AllomaMenu', verbose_name="Allomaga tegishli yo'nalishlar"),
        ),
        migrations.AlterField(
            model_name='regions',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Shahar nomi'),
        ),
    ]
