# Generated by Django 4.0.2 on 2022-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_alloma_options_alter_allomamenu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloma',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
