# Generated by Django 4.0.2 on 2022-06-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alloma_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alloma',
            name='count',
        ),
    ]
