# Generated by Django 4.0.2 on 2022-06-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_alloma_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='century',
            name='sum_madrasa',
        ),
        migrations.CreateModel(
            name='SumMadrasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_madrasa', models.CharField(max_length=100, null=True, verbose_name='Madrasalar soni')),
                ('century_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.century', verbose_name='Asrni tanlash')),
                ('region_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.regions', verbose_name='Shaharni tanlash')),
            ],
            options={
                'verbose_name': 'Madrasalar soni ',
                'verbose_name_plural': 'Madrasalar soni ',
            },
        ),
    ]
