# Generated by Django 4.0.2 on 2022-06-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_century_century_alter_regions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadrasaName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Madrasa nomi')),
            ],
        ),
        migrations.RemoveField(
            model_name='madrasa',
            name='name',
        ),
        migrations.AlterField(
            model_name='summadrasa',
            name='century_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.century', verbose_name='Asr '),
        ),
        migrations.AlterField(
            model_name='summadrasa',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.regions', verbose_name='Shahar '),
        ),
        migrations.AlterField(
            model_name='summadrasa',
            name='sum_madrasa',
            field=models.CharField(max_length=100, null=True, verbose_name='Madrasalar soni '),
        ),
        migrations.AddField(
            model_name='madrasa',
            name='madrasa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.madrasaname', verbose_name='Madrasa'),
        ),
    ]
