# Generated by Django 4.0.2 on 2022-06-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_madrasaname_remove_madrasa_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='madrasaname',
            options={'verbose_name': 'Madrasa nomi ', 'verbose_name_plural': 'Madrasalar nomlari '},
        ),
    ]
