# Generated by Django 4.0.2 on 2022-06-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0008_remove_woscience_author_id_remove_subject_menu_and_more'),
        ('base', '0017_alter_madrasaname_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloma',
            name='subject_id',
            field=models.ManyToManyField(blank=True, null=True, to='trunk.Subject', verbose_name='Fanlar'),
        ),
        migrations.CreateModel(
            name='WoScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name="Ma'lumot")),
                ('image', models.ImageField(upload_to='images', verbose_name="Rasm Qo'shish")),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.alloma', verbose_name='Ish Muallifi')),
            ],
            options={
                'verbose_name': "Jahon ilm-faniga qo'shgan hissasi ",
                'verbose_name_plural': "Jahon ilm-faniga qo'shgan hissasi ",
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Asar nomi')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.alloma', verbose_name='Asar Muallifi')),
            ],
            options={
                'verbose_name': 'Ilmiy Asar ',
                'verbose_name_plural': 'Ilmiy Asarlar ',
            },
        ),
    ]
