# Generated by Django 4.0.2 on 2022-06-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0009_remove_subject_info_subject_and_more'),
        ('base', '0019_remove_books_author_id_alloma_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_info',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject_info',
            name='alloma_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.alloma', verbose_name="Ma'lumot tegishli bo'lgan Alloma"),
        ),
        migrations.AddField(
            model_name='subject_info',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trunk.subject', verbose_name="Ma'lumot tegishli bo'lgan Fan"),
        ),
    ]
